### ISSUE TITLE
This is jusr for pretraining BERT?

### ISSUE THREAD

**Issue by HaishuoFang** [guotong1988/BERT-multi-gpu#1]
I want to fine tune pretrained BERT through multi-gpu in estimator API. Can your code solve this problem? thx.

**Comment by guotong1988** [comment]
fine-tune do not need multi-gpu, one is enough.

**Comment by HaishuoFang** [comment]
文本较长，数据量也略大想快一点

**Comment by stevewyl** [comment]
@HaishuoFang Maybe this tutorial can help you. https://lambdalabs.com/blog/bert-multi-gpu-implementation-using-tensorflow-and-horovod-with-code/

**Comment by HaoyuHu** [comment]
> I want to fine tune pretrained BERT through multi-gpu in estimator API. Can your code solve this problem? thx.

@HaishuoFang This project may help you.
https://github.com/HaoyuHu/bert-multi-gpu

**Comment by eduOS** [comment]
@HaoyuHu How does your implementation differ from this one? Briefly.

**Comment by HaoyuHu** [comment]
> @HaoyuHu How does your implementation differ from this one? Briefly.

@eduOS Hi. I think the implementation of `guotong1988/BERT-multi-gpu/run_pretraining_gpu_v2.py` and mines is very similar. We all use `MirroredStrategy` to acheive Multi-GPU.
