### ISSUE TITLE
ImportError: No module named 'tensorflow.python.distribute.cross_device_ops'

### ISSUE THREAD

**Issue by yumath** [guotong1988/BERT-multi-gpu#10]
I have used TensorFlow-gpu-1.12.0 to run run_pretraining_gpu_v2.py, but got this problem. Is the version I am using wrong?

**Comment by guotong1988** [comment]
???

**Comment by yick2232** [comment]
> I have used TensorFlow-gpu-1.12.0 to run run_pretraining_gpu_v2.py, but got this problem. Is the version I am using wrong?

So, how to solve it?  Which version for Tensorflow? I got same problem.
