### ISSUE TITLE
模型学不到东西

### ISSUE THREAD

**Issue by yumath** [guotong1988/BERT-multi-gpu#11]
使用run_pretraining_gpu.py在6块卡上训练了50万轮之后，使用官方eval接口，mlm_acc为0 。说明模型没有学习到任何东西啊，使用到下游任务，也没有任何提高，跟随机初始化bert的特征抽取能力差不多。

**Comment by guotong1988** [comment]
loss下降了吗

**Comment by yumath** [comment]
@guotong1988 下降了，目前训练了46万轮，loss从10降到了0.8左右

**Comment by guotong1988** [comment]
原来呢

**Comment by yumath** [comment]
使用官方单卡训练的脚本，40万轮，大概loss降到1.1左右，mlm_acc在75左右。

**Comment by guotong1988** [comment]
有机会试试run_pretraining_gpu_v2.py

**Comment by yumath** [comment]
主要用v2跑的时候容易梯度爆炸，found Nan or Inf，我也不明白为什么。后来就换了v1这个跑

**Comment by guotong1988** [comment]
3楼是怎么回事？和你1楼说的不符啊

**Comment by yumath** [comment]
loss是在下降，但是你没给eval接口。我用官方的eval接口评估，acc为0

**Comment by guotong1988** [comment]
感觉是eval步骤的问题

**Comment by guotong1988** [comment]
我eval是用的直接把save的模型跑text similarity任务

**Comment by guotong1988** [comment]
你确定官方成功load模型文件了吗

**Comment by yumath** [comment]
load成功了。我在ner上fine-tune，v2训练四十多万轮的模型，比官方给的脚本单卡训练一万轮的模型还低，低10个百分点左右。所以我觉得没有学到东西。你使用过你这个接口pretrain出来的模型吗

**Comment by guotong1988** [comment]
https://github.com/guotong1988/BERT-multi-gpu#experiment-result

**Comment by guotong1988** [comment]
https://blog.csdn.net/guotong1988/article/details/100539565

**Comment by guotong1988** [comment]
官方的`run_classifier.py`不行，跑不出结果，得导入自己的相关代码

**Comment by guotong1988** [comment]
具体是global_step的问题

**Comment by guotong1988** [comment]
https://www.zhihu.com/question/422533522/answer/1490516551
