### ISSUE TITLE
Cannot reload pre-trained model

### ISSUE THREAD

**Issue by yick2232** [guotong1988/BERT-multi-gpu#12]
I got this error "Not found: Key bert/embeddings/LayerNorm/beta not found in checkpoint".

**Comment by guotong1988** [comment]
You could check the matching of tensor name.

**Comment by yick2232** [comment]
> You could check the exact match of tensor name.

嗯嗯，刚刚调试了一下，发现多了一个顶层scope
[https://github.com/guotong1988/BERT-multi-gpu/blob/master/run_pretraining_gpu.py#L630](url)
