### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.distribute.cross_device_ops

### ISSUE THREAD

**Issue by vanpersie32** [guotong1988/BERT-multi-gpu#13]
tensorflow version 1.12.0 ,import error ModuleNotFoundError: No module named 'tensorflow.python.distribute.cross_device_ops 
![image](https://user-images.githubusercontent.com/15981416/63591748-3db40700-c5e2-11e9-959d-79dc473594d5.png)

**Comment by guotong1988** [comment]
you can google it

**Comment by guotong1988** [comment]
Try TF 1.13?

**Comment by guotong1988** [comment]
try again https://github.com/guotong1988/BERT-multi-gpu/issues/18

**Comment by shuxiaobo** [comment]
Still reproduce this error by v2.

**Comment by guotong1988** [comment]
I did not encounter this problem. If someone solved it please tell us. Thank you.

**Comment by guotong1988** [comment]
Try `tf.contrib.distribute.AllReduceCrossDeviceOps as AllReduceCrossDeviceOps`

**Comment by shuxiaobo** [comment]
I just upgrade my tensorflow to 1.14, the error does not rised
