### ISSUE TITLE
run_pretraining_gpu.py not working

### ISSUE THREAD

**Issue by 652994331** [guotong1988/BERT-multi-gpu#16]
Hi, could anyone one help me with this problem, after  i changed the parameters above, then I run the run_pretraining_gpu.py and the thing is like this. As you can see, just stop here even after a long time. Please help, thanks
![image](https://user-images.githubusercontent.com/51428350/63726027-ed6ebc00-c810-11e9-8899-93766c2dd50f.png)

**Comment by guotong1988** [comment]
I guess you installed the CPU version of TensorFlow

**Comment by guotong1988** [comment]
export CUDA_VISIBLE_DEVICES=0,1,2,3
??

**Comment by gaozhanfire** [comment]
我也遇到了这个错误，export之后还是不行

**Comment by guotong1988** [comment]
谁解决了可以分享下…

**Comment by guotong1988** [comment]
更新了，可以重新试试
https://github.com/guotong1988/BERT-multi-gpu/issues/18
