### ISSUE TITLE
运行create_pretraining_data.py报错

### ISSUE THREAD

**Issue by KAIKAIZHANG** [guotong1988/BERT-multi-gpu#2]

**Comment by KAIKAIZHANG** [comment]
![qq 20190228144627](https://user-images.githubusercontent.com/16151674/53546559-a9537500-3b67-11e9-8647-229efbd4d652.png)

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/53546884-7e1d5580-3b68-11e9-9949-172904162ebf.png)
把这句话修改成你的数据文件
