### ISSUE TITLE
I wonder why is the reshaping necessary?

### ISSUE THREAD

**Issue by eduOS** [guotong1988/BERT-multi-gpu#7]
I thought [this line](https://github.com/guotong1988/BERT-multi-gpu/blob/master/modeling.py#L425) is unnecessary and can lead to errors triggered by [this line](https://github.com/google-research/bert/blob/master/modeling.py#L465). Am I missing something?

**Comment by guotong1988** [comment]
That line is same to the origin official BERT. I haven't changed it.
