### ISSUE TITLE
ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.

### ISSUE THREAD

**Issue by nlp4whp** [guotong1988/BERT-multi-gpu#8]
Does anyone meet this error:

```
ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.
```

my tensorflow version is **1.10.0**, I wanna know whether the tensorflow version causes this error

**Comment by guotong1988** [comment]
Try https://github.com/guotong1988/BERT-multi-gpu/blob/master/run_pretraining_gpu_v2.py

**Comment by nlp4whp** [comment]
> Try https://github.com/guotong1988/BERT-multi-gpu/blob/master/run_pretraining_gpu_v2.py

Thanks, it works when I update my tf to 1.12.0
